import '../models/wash_models.dart';

class MockOrderFixtures {
  static List<WashOrder> initialOrders() {
    return [
      WashOrder(
        id: 'LAV-1004',
        request: WashRequest(
          serviceType: 'mobile_car_wash',
          packageId: 'express',
          packageName: 'Express',
          vehicleTypeId: 'suv',
          vehicleTypeName: 'SUV',
          address: 'Roma Norte, CDMX',
          latitude: 19.41952,
          longitude: -99.16765,
          scheduleId: 'now',
          scheduleLabel: 'Disponible - Ahora mismo',
          notes: 'Cliente solicita confirmacion por mensaje',
          servicePrice: 99,
          travelFee: 20,
          totalPrice: 119,
          estimatedMinutes: 25,
          currency: 'MXN',
          status: RequestLifecycleStatus.confirmed,
          createdAt: DateTime.now().toUtc(),
        ),
        status: OrderStatus.searching,
        customerEmail: 'cliente@lavify.app',
        assignedWasherName: 'Sin asignar',
        assignedWorkerEmail: null,
        assignedVehicleLabel: 'Por definir',
        createdAt: DateTime.now(),
        etaMinutes: 25,
      ),
      WashOrder(
        id: 'LAV-1001',
        request: WashRequest(
          serviceType: 'mobile_car_wash',
          packageId: 'premium',
          packageName: 'Premium',
          vehicleTypeId: 'sedan',
          vehicleTypeName: 'Sedan mediano',
          address: 'Av. Reforma 245, CDMX',
          latitude: 19.432608,
          longitude: -99.133209,
          scheduleId: 'today_630',
          scheduleLabel: 'Hoy - 6:30 PM',
          notes: '',
          servicePrice: 199,
          travelFee: 20,
          totalPrice: 219,
          estimatedMinutes: 35,
          currency: 'MXN',
          status: RequestLifecycleStatus.assigned,
          createdAt: DateTime.now().toUtc(),
        ),
        status: OrderStatus.assigned,
        customerEmail: 'cliente@lavify.app',
        assignedWasherName: 'Carlos M.',
        assignedWorkerEmail: 'lavador@lavify.app',
        assignedVehicleLabel: 'Unidad eco 07',
        createdAt: DateTime.now(),
        etaMinutes: 18,
      ),
      WashOrder(
        id: 'LAV-0998',
        request: WashRequest(
          serviceType: 'mobile_car_wash',
          packageId: 'full-care',
          packageName: 'Full Care',
          vehicleTypeId: 'compact',
          vehicleTypeName: 'Compacto',
          address: 'Polanco, CDMX',
          latitude: 19.433,
          longitude: -99.2,
          scheduleId: 'yesterday_1100',
          scheduleLabel: 'Ayer - 11:00 AM',
          notes: 'Llamar al llegar',
          servicePrice: 149,
          travelFee: 20,
          totalPrice: 169,
          estimatedMinutes: 40,
          currency: 'MXN',
          status: RequestLifecycleStatus.completed,
          createdAt: DateTime.now().subtract(const Duration(days: 1)).toUtc(),
        ),
        status: OrderStatus.completed,
        customerEmail: 'cliente2@lavify.app',
        assignedWasherName: 'Andrea R.',
        assignedWorkerEmail: 'lavador2@lavify.app',
        assignedVehicleLabel: 'Unidad eco 03',
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
        etaMinutes: 0,
      ),
    ];
  }
}
